import type { Metadata } from "next";
import "./globals.css";
import { Lexend_Exa } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const lexendExa = Lexend_Exa({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-lexend-exa", // Add CSS variable
});

export const metadata: Metadata = {
  title: "Shabhi's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendExa.variable} ${lexendExa.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
